CREATE TABLE clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    company_name VARCHAR(255),
    industry VARCHAR(100),
    website_url TEXT,
    client_type VARCHAR(50) DEFAULT 'general' CHECK (client_type IN ('general',
    'local_seo',
    'ecommerce',
    'enterprise')),
    status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active',
    'inactive',
    'pending',
    'on_hold')),
    performance_status VARCHAR(20) DEFAULT 'green' CHECK (performance_status IN ('green',
    'yellow',
    'red')),
    assigned_admin_id UUID,
    onboarding_completed BOOLEAN DEFAULT false,
    monthly_budget DECIMAL(10,2),
    contract_start_date DATE,
    contract_end_date DATE,
    billing_cycle VARCHAR(50),
    last_contact_date TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);